[package]
name = "mothra"
version = "0.1.0"
authors = ["Jonny Rhea <jonny.rhea@consensys.net>"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml"
]

[workspace]
members = [
    "libp2p-wrapper",
    "ffi",
    "examples/rust"
]

[dependencies]
libp2p-wrapper =  { path = "libp2p-wrapper" }
parking_lot = "0.9.0"
slog-term = "^2.4.0"
slog-async = "^2.3.0"
slog = { version = "2.5.2" , features = ["max_level_trace"] }
ctrlc = { version = "3.1.1", features = ["termination"] }
bs58 = "0.2.0"
getopts = "0.2"
cast = "0.2.2"
clap = "2.32.0"
serde = "1.0.102"
serde_derive = "1.0.102"
tokio = "0.1.22"
futures = "0.1.29"
exit-future = "0.1.4"
error-chain = "0.12.0"
dirs = "2.0.1"
smallvec = "1.0.0"
fnv = "1.0.6"
unsigned-varint = "0.2.3"
bytes = "0.4.12"
env_logger = "0.6.0"
rand = "0.7.2"

[patch.crates-io]
tree_hash = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "tree_hash" }
tree_hash_derive = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "tree_hash_derive" }
eth2_ssz = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "eth2_ssz" }
eth2_ssz_derive = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "eth2_ssz_derive" }
eth2_ssz_types = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "eth2_ssz_types" }
types = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "types" }
eth2_hashing = { git = "https://github.com/sigp/lighthouse", rev = "d7e29382967c16a7a4ce73d1672867523287402b", package = "eth2_hashing" }

