[package]
name = "rust-example"
version = "0.1.0"
authors = ["Jonny Rhea <jonny.rhea@consensys.net>"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml"
]

[dependencies]
mothra = { path = "../../core"}
tokio = "0.1.16"
slog = { version = "^2.2.3" , features = ["max_level_trace"] }
